# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/


services:
  portfolioapp-client:
    container_name: client
    build:
      context: ./portfolioapp.client
      args: 
        CLIENT_RUN_COMMAND: ${CLIENT_RUN_COMMAND}
    image: ${DOCKER_REPOSITORY}:client
    depends_on:
      - portfolioapp-database
    environment:
      NODE_ENV: ${ENVIRONMENT}
      CLIENT_RUN_COMMAND: ${CLIENT_RUN_COMMAND}
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./portfolioapp.client/package.json
          action: rebuild
        - path: ./portfolioapp.client/src
          target: /app/src
          action: sync
    volumes:
      -  ./PortfolioAppPrivate/certificates/client:/etc/ssl/certs:ro

  portfolioapp-server:
    container_name: server
    build:
      context: ./PortfolioApp.server
      args:
        API_PORT: ${API_PORT}
    image: ${DOCKER_REPOSITORY}:server
    depends_on:
      - portfolioapp-database
    environment:
      DOTNET_ENVIRONMENT: ${ENVIRONMENT}
      DOTNET_HTTPS_PORTS: ${API_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      CORS_HOST: ${CORS_HOST}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${SERVER_CERT_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${SERVER_CERT_PATH}
    ports:
      - ${API_PORT}:${API_PORT}
    develop:
      watch:
        - path: ./PortfolioApp.Server
          action: rebuild
    volumes:
      -  ./PortfolioAppPrivate/certificates/server:/https:ro

  portfolioapp-database:
    container_name: db
    build:
      context: ./portfolioapp.db
    image: ${DOCKER_REPOSITORY}:db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes: 
      - database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017

volumes:
  database:
